### ISSUE TITLE
not working plugin, i have purechat 

### ISSUE THREAD

**Issue by SuperAdam47** [WORTI3/PC-CustomList#1]
[12:45:01] [Server thread/CRITICAL]: [CustomList] PureChat was not found, Plugin: CustomList Disabled

**Comment by aircwo** [comment]
Are you sure it was PureChat you had installed and not PurePerms. PurePerms should also be installed.

**Comment by SuperAdam47** [comment]
i have purechat and pureperms this plugins working with no errors

**Comment by aircwo** [comment]
Tested and working
